# Generated by Django 4.2.21 on 2026-03-25 15:22

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


def add_estado_column_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'programacion_dia'
              AND COLUMN_NAME = 'estado'
            """
        )
        exists = cursor.fetchone()[0] > 0

        if not exists:
            cursor.execute(
                """
                ALTER TABLE `programacion_dia`
                ADD COLUMN `estado` VARCHAR(20) NOT NULL DEFAULT 'programada'
                """
            )


def set_dinamizador_planta(apps, schema_editor):
    Usuario = apps.get_model('academico', 'Usuario')
    Usuario.objects.filter(id_rol__nombre__icontains='dinamizador').update(tipo_contrato=1)


def set_planta_limits(apps, schema_editor):
    Usuario = apps.get_model('academico', 'Usuario')
    Usuario.objects.filter(tipo_contrato=1).update(
        horas_max_mensual=120,
        horas_objetivo_anual=1200,
        horas_min_mensual=100,
        horas_min_anual=1000,
    )


def noop_reverse(apps, schema_editor):
    pass


def drop_legacy_usuario_columns(apps, schema_editor):
    legacy_columns = (
        'horas_meta_anual',
        'horas_mes_min',
        'horas_mes_max',
    )
    with schema_editor.connection.cursor() as cursor:
        for column in legacy_columns:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'usuario'
                  AND COLUMN_NAME = %s
                """,
                [column],
            )
            exists = cursor.fetchone()[0] > 0
            if exists:
                cursor.execute(f"ALTER TABLE `usuario` DROP COLUMN `{column}`")

class Migration(migrations.Migration):

    replaces = [('academico', '0001_squashed_0013_set_planta_hour_limits'), ('academico', '0002_drop_legacy_usuario_hour_columns'), ('academico', '0003_alter_ambiente_ambiente'), ('academico', '0004_programaciondia_horario_especial'), ('academico', '0005_radicado'), ('academico', '0006_radicado_dias_seleccionados'), ('academico', '0007_remove_radicado_fechas')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('ambiente', models.CharField(max_length=120, unique=True)),
                ('lugar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ambiente',
            },
        ),
        migrations.CreateModel(
            name='EquipoEjecutor',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'equipo_ejecutor',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=120, unique=True)),
                ('horas', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id_programa_formacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('horas_max', models.IntegerField()),
                ('horas_lectiva', models.IntegerField()),
                ('horas_productivas', models.IntegerField()),
            ],
            options={
                'db_table': 'programa_formacion',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id_tipodoc', models.AutoField(primary_key=True, serialize=False)),
                ('tipodoc', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_doc',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo_competencia', models.CharField(choices=[('tecnica', 'Técnica'), ('trasversal', 'Trasversal')], max_length=10)),
                ('horas_max', models.IntegerField()),
                ('id_programa_formacion', models.ForeignKey(db_column='id_programa_formacion', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.programaformacion')),
            ],
            options={
                'db_table': 'competencia',
                'unique_together': {('id_programa_formacion', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.competencia')),
            ],
            options={
                'db_table': 'resultado',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField()),
                ('id_equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.equipoejecutor')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.rol')),
                ('id_tipodoc', models.ForeignKey(db_column='id_tipodoc', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.tipodoc')),
                ('horas_max_mensual', models.PositiveSmallIntegerField(default=160)),
                ('horas_min_mensual', models.PositiveSmallIntegerField(default=140)),
                ('horas_objetivo_anual', models.IntegerField(default=1680)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='EquipoPrograma',
            fields=[
                ('id_equipo_programa', models.AutoField(primary_key=True, serialize=False)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.equipoejecutor')),
                ('id_programa_formacion', models.ForeignKey(db_column='id_programa_formacion', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.programaformacion')),
            ],
            options={
                'db_table': 'equipo_programa',
                'unique_together': {('id_equipo', 'id_programa_formacion')},
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('codigo_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_ficha', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_ambiente', models.ForeignKey(db_column='id_ambiente', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.ambiente')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.equipoejecutor')),
                ('id_horario', models.ForeignKey(blank=True, db_column='id_horario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.horario')),
                ('codigo_municipio', models.ForeignKey(db_column='codigo_municipio', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.municipio')),
                ('id_programa_formacion', models.ForeignKey(db_column='id_programa_formacion', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.programaformacion')),
                ('id_lider_ficha', models.ForeignKey(blank=True, db_column='id_lider_ficha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas_lideradas', to='academico.usuario')),
            ],
            options={
                'db_table': 'ficha',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionDia',
            fields=[
                ('id_programacion_dia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horas_dia', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(default='programada', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo_ficha', models.ForeignKey(db_column='codigo_ficha', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.ficha')),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.competencia')),
                ('id_dinamizador_asignador', models.ForeignKey(db_column='id_dinamizador_asignador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='programaciones_dia_dinamizador', to='academico.usuario')),
                ('id_horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.horario')),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='programaciones_dia_instructor', to='academico.usuario')),
            ],
            options={
                'db_table': 'programacion_dia',
                'unique_together': {('codigo_ficha', 'fecha', 'id_horario', 'id_instructor')},
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id_programacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('creado_en', models.DateTimeField()),
                ('codigo_ficha', models.ForeignKey(db_column='codigo_ficha', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.ficha')),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.competencia')),
                ('id_dinamizador_asignador', models.ForeignKey(db_column='id_dinamizador_asignador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='programaciones_dinamizador', to='academico.usuario')),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='programaciones_instructor', to='academico.usuario')),
                ('anio_operativo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('ejecutada', 'Ejecutada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('mes_operativo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(blank=True, db_column='id_ambiente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.ambiente')),
            ],
            options={
                'db_table': 'programacion',
            },
        ),
        migrations.AddField(
            model_name='ambiente',
            name='codigo_municipio',
            field=models.ForeignKey(blank=True, db_column='codigo_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academico.municipio'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='programaciondia',
                    unique_together={('codigo_ficha', 'fecha', 'id_instructor')},
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionDiaResultado',
            fields=[
                ('id_programacion_dia_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_programacion_dia', models.ForeignKey(db_column='id_programacion_dia', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.programaciondia')),
                ('id_resultado', models.ForeignKey(db_column='id_resultado', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.resultado')),
            ],
            options={
                'db_table': 'programacion_dia_resultado',
                'unique_together': {('id_programacion_dia', 'id_resultado')},
            },
        ),
        migrations.RunPython(
            code=add_estado_column_if_missing,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='programacion',
            name='modificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacion',
            name='razon_cambio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programaciondia',
            name='id_usuario_modificacion',
            field=models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programaciones_dia_modificadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='programaciondia',
            name='modificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('ajustada', 'Ajustada'), ('reemplazada', 'Reemplazada'), ('ejecutada', 'Ejecutada'), ('cancelada', 'Cancelada')], default='programada', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_contrato',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(
            code=set_dinamizador_planta,
            reverse_code=noop_reverse,
        ),
        migrations.AddField(
            model_name='usuario',
            name='horas_min_anual',
            field=models.IntegerField(default=1680),
        ),
        migrations.RunPython(
            code=set_planta_limits,
            reverse_code=noop_reverse,
        ),
        migrations.RunPython(
            code=drop_legacy_usuario_columns,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ambiente',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='programaciondia',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaciondia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Radicado',
            fields=[
                ('id_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_radicado', models.CharField(max_length=180)),
                ('tipo_radicado', models.PositiveSmallIntegerField()),
                ('descripcion_radicado', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('archivo_excel', models.FileField(upload_to='radicados/')),
                ('aprobado', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='radicados_instructor', to='academico.usuario')),
                ('dias_seleccionados', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'radicado',
            },
        ),
    ]
