# Generated by Django 4.2.21 on 2026-04-07 14:00

import academico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_radicado_campos_actividad_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicado',
            name='archivo_excel',
            field=models.FileField(upload_to=academico.models.ruta_archivo_radicado),
        ),
    ]
