# Generated by Django 4.2.21 on 2026-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_radicado_archivo_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_dinamizador',
            field=models.CharField(blank=True, choices=[('instructor', 'Dinamizador-Instructor'), ('coordinador', 'Dinamizador-Coordinador')], max_length=15, null=True),
        ),
    ]
