# Generated by Django 4.2.21 on 2026-04-09 13:03

from django.db import migrations


def populate_tipo_dinamizador(apps, schema_editor):
    Usuario = apps.get_model('academico', 'Usuario')
    Rol = apps.get_model('academico', 'Rol')
    rol_din = Rol.objects.filter(nombre__icontains='dinamizador').first()
    if rol_din:
        Usuario.objects.filter(id_rol=rol_din, tipo_dinamizador__isnull=True).update(
            tipo_dinamizador='instructor',
        )


def reverse_populate(apps, schema_editor):
    Usuario = apps.get_model('academico', 'Usuario')
    Usuario.objects.filter(tipo_dinamizador__isnull=False).update(tipo_dinamizador=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_add_tipo_dinamizador'),
    ]

    operations = [
        migrations.RunPython(populate_tipo_dinamizador, reverse_populate),
    ]
