# Generated by Django 4.2.21 on 2026-04-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_coordinador_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionResultado',
            fields=[
                ('id_programacion_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('horas_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('id_programacion', models.ForeignKey(db_column='id_programacion', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.programacion')),
                ('id_resultado', models.ForeignKey(db_column='id_resultado', on_delete=django.db.models.deletion.DO_NOTHING, to='academico.resultado')),
            ],
            options={
                'db_table': 'programacion_resultado',
                'unique_together': {('id_programacion', 'id_resultado')},
            },
        ),
    ]
