# Generated by Django 4.2.21 on 2026-04-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_programacionresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionresultado',
            name='horas_dictadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
