# Generated by Django 4.2.21 on 2026-04-13 18:11

from django.db import migrations


MUNICIPIOS_CAUCA = [
    (19001, 'popayan'),
    (19022, 'almaguer'),
    (19050, 'argelia'),
    (19075, 'balboa'),
    (19100, 'bolivar'),
    (19110, 'buenos aires'),
    (19130, 'cajibio'),
    (19137, 'caldono'),
    (19142, 'caloto'),
    (19212, 'corinto'),
    (19256, 'el tambo'),
    (19290, 'florencia'),
    (19300, 'guachene'),
    (19318, 'guapi'),
    (19355, 'inza'),
    (19364, 'jambalo'),
    (19392, 'la sierra'),
    (19397, 'la vega'),
    (19418, 'lopez de micay'),
    (19450, 'mercaderes'),
    (19455, 'miranda'),
    (19473, 'morales'),
    (19513, 'padilla'),
    (19517, 'paez'),
    (19532, 'patia'),
    (19533, 'piamonte'),
    (19548, 'piendamo'),
    (19573, 'puerto tejada'),
    (19585, 'purace'),
    (19622, 'rosas'),
    (19693, 'san sebastian'),
    (19698, 'santander de quilichao'),
    (19701, 'santa rosa'),
    (19743, 'silvia'),
    (19760, 'sotara'),
    (19780, 'suarez'),
    (19785, 'sucre'),
    (19807, 'timbio'),
    (19809, 'timbiqui'),
    (19821, 'toribio'),
    (19824, 'totoro'),
    (19845, 'villa rica'),
]


def cargar_municipios_cauca(apps, schema_editor):
    Municipio = apps.get_model('academico', 'Municipio')

    for codigo, nombre in MUNICIPIOS_CAUCA:
        Municipio.objects.update_or_create(
            codigo_municipio=codigo,
            defaults={'municipio': nombre},
        )


def revertir_municipios_cauca(apps, schema_editor):
    # No se elimina data en reversa para evitar pérdida accidental de referencias.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_programacionresultado_horas_dictadas'),
    ]

    operations = [
        migrations.RunPython(cargar_municipios_cauca, revertir_municipios_cauca),
    ]
